<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

namespace GPBMetadata;

class Grpc
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (true == static::$is_initialized)
        {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            '0ac2010a0a677270632e70726f746f120467727063222f0a0c4c6f67696e' .
            '52657175657374120d0a0570686f6e6518012001280912100a0870617373' .
            '776f7264180220012809222f0a0d4c6f67696e526573706f6e7365120f0a' .
            '0773756363657373180120012808120d0a056572726f7218022001280932' .
            '3f0a0b417574685365727669636512300a054c6f67696e12122e67727063' .
            '2e4c6f67696e526571756573741a132e677270632e4c6f67696e52657370' .
            '6f6e73654203d00201620670726f746f33'
        ), true);

        static::$is_initialized = true;
    }
}
