<?php

declare(strict_types=1);

namespace Imi\Server\Http\Message\Proxy;

use Imi\RequestContextProxy\Annotation\RequestContextProxy;
use Imi\RequestContextProxy\BaseRequestContextProxy;

/**
 * @RequestContextProxy(class="Imi\Server\Http\Message\Contract\IHttpResponse", name="response")
 *
 * @method        static                                                              redirect(string $url, int $status = 302)
 * @method static static                                                              redirect(string $url, int $status = 302)
 * @method        static                                                              send()
 * @method static static                                                              send()
 * @method        static                                                              sendFile(string $filename, ?string $contentType = NULL, ?string $outputFileName = NULL, int $offset = 0, int $length = 0)
 * @method static static                                                              sendFile(string $filename, ?string $contentType = NULL, ?string $outputFileName = NULL, int $offset = 0, int $length = 0)
 * @method        bool                                                                isHeaderWritable()
 * @method static bool                                                                isHeaderWritable()
 * @method        bool                                                                isBodyWritable()
 * @method static bool                                                                isBodyWritable()
 * @method        static                                                              withResponseBodyEmitter(?\Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter $responseBodyEmitter)
 * @method static static                                                              withResponseBodyEmitter(?\Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter $responseBodyEmitter)
 * @method        static                                                              setResponseBodyEmitter(?\Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter $responseBodyEmitter)
 * @method static static                                                              setResponseBodyEmitter(?\Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter $responseBodyEmitter)
 * @method        \Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter|null getResponseBodyEmitter()
 * @method static \Imi\Server\Http\Message\Emitter\Contract\IResponseBodyEmitter|null getResponseBodyEmitter()
 * @method        static                                                              setStatus(int $code, string $reasonPhrase = '')
 * @method static static                                                              setStatus(int $code, string $reasonPhrase = '')
 * @method        static                                                              withCookie(string $key, string $value, int $expire = 0, string $path = '/', string $domain = '', bool $secure = false, bool $httponly = false)
 * @method static static                                                              withCookie(string $key, string $value, int $expire = 0, string $path = '/', string $domain = '', bool $secure = false, bool $httponly = false)
 * @method        static                                                              setCookie(string $key, string $value, int $expire = 0, string $path = '/', string $domain = '', bool $secure = false, bool $httponly = false)
 * @method static static                                                              setCookie(string $key, string $value, int $expire = 0, string $path = '/', string $domain = '', bool $secure = false, bool $httponly = false)
 * @method        array                                                               getCookieParams()
 * @method static array                                                               getCookieParams()
 * @method        array|null                                                          getCookie(string $name, ?array $default = NULL)
 * @method static array|null                                                          getCookie(string $name, ?array $default = NULL)
 * @method        array                                                               getTrailers()
 * @method static array                                                               getTrailers()
 * @method        bool                                                                hasTrailer(string $name)
 * @method static bool                                                                hasTrailer(string $name)
 * @method        string|null                                                         getTrailer(string $name)
 * @method static string|null                                                         getTrailer(string $name)
 * @method        static                                                              withTrailer(string $name, string $value)
 * @method static static                                                              withTrailer(string $name, string $value)
 * @method        static                                                              setTrailer(string $name, string $value)
 * @method static static                                                              setTrailer(string $name, string $value)
 * @method        int                                                                 getStatusCode()
 * @method static int                                                                 getStatusCode()
 * @method        static                                                              withStatus(int $code, string $reasonPhrase = '')
 * @method static static                                                              withStatus(int $code, string $reasonPhrase = '')
 * @method        string                                                              getReasonPhrase()
 * @method static string                                                              getReasonPhrase()
 * @method        string                                                              getProtocolVersion()
 * @method static string                                                              getProtocolVersion()
 * @method        static                                                              withProtocolVersion(string $version)
 * @method static static                                                              withProtocolVersion(string $version)
 * @method        string[][]                                                          getHeaders()
 * @method static string[][]                                                          getHeaders()
 * @method        bool                                                                hasHeader(string $name)
 * @method static bool                                                                hasHeader(string $name)
 * @method        string[]                                                            getHeader(string $name)
 * @method static string[]                                                            getHeader(string $name)
 * @method        string                                                              getHeaderLine(string $name)
 * @method static string                                                              getHeaderLine(string $name)
 * @method        static                                                              withHeader(string $name, $value)
 * @method static static                                                              withHeader(string $name, $value)
 * @method        static                                                              withAddedHeader(string $name, $value)
 * @method static static                                                              withAddedHeader(string $name, $value)
 * @method        static                                                              withoutHeader(string $name)
 * @method static static                                                              withoutHeader(string $name)
 * @method        \Psr\Http\Message\StreamInterface                                   getBody()
 * @method static \Psr\Http\Message\StreamInterface                                   getBody()
 * @method        static                                                              withBody(\Psr\Http\Message\StreamInterface $body)
 * @method static static                                                              withBody(\Psr\Http\Message\StreamInterface $body)
 * @method        static                                                              setProtocolVersion(string $version)
 * @method static static                                                              setProtocolVersion(string $version)
 * @method        static                                                              setHeader(string $name, array|string $value)
 * @method static static                                                              setHeader(string $name, array|string $value)
 * @method        static                                                              addHeader(string $name, array|string $value)
 * @method static static                                                              addHeader(string $name, array|string $value)
 * @method        static                                                              removeHeader(string $name)
 * @method static static                                                              removeHeader(string $name)
 * @method        static                                                              setBody(\Psr\Http\Message\StreamInterface $body)
 * @method static static                                                              setBody(\Psr\Http\Message\StreamInterface $body)
 */
class ResponseProxy extends BaseRequestContextProxy
{
}
