<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

namespace Grpc;

/**
 * Protobuf type <code>grpc.AuthService</code>.
 */
interface AuthServiceInterface
{
    /**
     * Method <code>login</code>.
     *
     * @param \Grpc\LoginRequest $request
     *
     * @return \Grpc\LoginResponse
     */
    public function login(LoginRequest $request);
}
