<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

namespace Grpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.LoginResponse</code>.
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * 错误信息.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     */
    private $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     *     @var bool
     *           是否成功
     *     @var string
     *           错误信息
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Grpc::initOnce();
        parent::__construct($data);
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * 是否成功
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * 错误信息.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     *
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * 错误信息.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     *
     * @param string $var
     *
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, true);
        $this->error = $var;

        return $this;
    }
}
