<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace Grpc;

/**
 * Protobuf type <code>grpc.TestService</code>
 */
interface TestServiceInterface
{
    /**
     * Method <code>test</code>
     *
     * @param \Grpc\TestRequest $request
     * @return \Grpc\TestRequest
     */
    public function test(\Grpc\TestRequest $request);

}

